import "./globals.css";
import { Prompt } from "next/font/google";
import AuthWrapper from "@/components/Authwrapper";
import TailwindIndicator from "@/components/tailwind-indicator";

// const inter = Inter({ subsets: ["latin"] });
const prompts = Prompt({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata = {
  title: "Storage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthWrapper>
      <html lang="en">
        <body className={prompts.className}>
          <div>{children}</div>
          <TailwindIndicator />
        </body>
      </html>
    </AuthWrapper>
  );
}
